name: video_player_manager
description: "A lightweight, singleton-based video controller for Flutter that simplifies managing a single active VideoPlayerController across your entire application."
version: 0.0.2
repository: https://github.com/Yogesh-droid/video_player_manager
issue_tracker: https://github.com/Yogesh-droid/video_player_manager/issues

environment:
  sdk: ^3.10.7
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
